package pe.egcc.censoapp.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import pe.egcc.censoapp.controller.CensoController;
import pe.egcc.censoapp.model.Censo;

public class ListavoView extends javax.swing.JInternalFrame {

  private CensoController censoController;
  
  public ListavoView() {
    initComponents();
    censoController = new CensoController();
    llenarTabla();
  }
  
  private void llenarTabla(){
    
    // Datos
    List<Censo> listado = censoController.leerCensos();
    
    // Acceso a la tabla
    DefaultTableModel tabla = (DefaultTableModel) tblRepo.getModel();
    tabla.setRowCount(0);
    
    // LLenar tabla
    for (Censo censo : listado) {
      Object[] rowData = {censo.getNombre(), censo.getEdad(), censo.getSexo(), censo.getInstruccion()};
      tabla.addRow(rowData);
    }
    
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblRepo = new javax.swing.JTable();

    setClosable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("LISTADO DE CENSOS");

    tblRepo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    tblRepo.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "NOMBRE", "EDAD", "SEXO", "INSTRUCCION"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, true, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tblRepo.setRowHeight(30);
    jScrollPane1.setViewportView(tblRepo);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblRepo;
  // End of variables declaration//GEN-END:variables
}
